// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: ksr_nb_api.proto

// Package ksrapi defines the data model for KSR plugin's northbound API.

package ksrapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KsrStats holds statistics for an individual KSR type
type KsrStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of add operations.
	Adds uint64 `protobuf:"varint,1,opt,name=Adds,proto3" json:"Adds,omitempty"`
	// Number of delete operations.
	Updates uint64 `protobuf:"varint,2,opt,name=Updates,proto3" json:"Updates,omitempty"`
	// Number of delete operations.
	Deletes uint64 `protobuf:"varint,3,opt,name=Deletes,proto3" json:"Deletes,omitempty"`
	// Number of data store resync runs.
	Resyncs uint64 `protobuf:"varint,4,opt,name=Resyncs,proto3" json:"Resyncs,omitempty"`
	// Number of add operation errors.
	AddErrors uint64 `protobuf:"varint,5,opt,name=AddErrors,proto3" json:"AddErrors,omitempty"`
	// Number of delete operation errors.
	UpdErrors uint64 `protobuf:"varint,6,opt,name=UpdErrors,proto3" json:"UpdErrors,omitempty"`
	// Number of delete operation errors.
	DelErrors uint64 `protobuf:"varint,7,opt,name=DelErrors,proto3" json:"DelErrors,omitempty"`
	// Number of operations where one or more arguments were invalid.
	ArgErrors uint64 `protobuf:"varint,8,opt,name=ArgErrors,proto3" json:"ArgErrors,omitempty"`
	// Number of of data store resync errors.
	ResErrors uint64 `protobuf:"varint,9,opt,name=ResErrors,proto3" json:"ResErrors,omitempty"`
}

func (x *KsrStats) Reset() {
	*x = KsrStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ksr_nb_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KsrStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KsrStats) ProtoMessage() {}

func (x *KsrStats) ProtoReflect() protoreflect.Message {
	mi := &file_ksr_nb_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KsrStats.ProtoReflect.Descriptor instead.
func (*KsrStats) Descriptor() ([]byte, []int) {
	return file_ksr_nb_api_proto_rawDescGZIP(), []int{0}
}

func (x *KsrStats) GetAdds() uint64 {
	if x != nil {
		return x.Adds
	}
	return 0
}

func (x *KsrStats) GetUpdates() uint64 {
	if x != nil {
		return x.Updates
	}
	return 0
}

func (x *KsrStats) GetDeletes() uint64 {
	if x != nil {
		return x.Deletes
	}
	return 0
}

func (x *KsrStats) GetResyncs() uint64 {
	if x != nil {
		return x.Resyncs
	}
	return 0
}

func (x *KsrStats) GetAddErrors() uint64 {
	if x != nil {
		return x.AddErrors
	}
	return 0
}

func (x *KsrStats) GetUpdErrors() uint64 {
	if x != nil {
		return x.UpdErrors
	}
	return 0
}

func (x *KsrStats) GetDelErrors() uint64 {
	if x != nil {
		return x.DelErrors
	}
	return 0
}

func (x *KsrStats) GetArgErrors() uint64 {
	if x != nil {
		return x.ArgErrors
	}
	return 0
}

func (x *KsrStats) GetResErrors() uint64 {
	if x != nil {
		return x.ResErrors
	}
	return 0
}

// Stats holds aggregated statistics for all KSR types in the KSR process.
type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Statistics for the Namespace Reflector
	NamespaceStats *KsrStats `protobuf:"bytes,1,opt,name=namespaceStats,proto3" json:"namespaceStats,omitempty"`
	// Statistics for the Pod Reflector
	PodStats *KsrStats `protobuf:"bytes,2,opt,name=podStats,proto3" json:"podStats,omitempty"`
	// Statistics for the Network Policy Reflector
	PolicyStats *KsrStats `protobuf:"bytes,3,opt,name=policyStats,proto3" json:"policyStats,omitempty"`
	// Statistics for the Endpoints Reflector
	EndpointsStats *KsrStats `protobuf:"bytes,4,opt,name=endpointsStats,proto3" json:"endpointsStats,omitempty"`
	// Statistics for the Service Reflector
	ServiceStats *KsrStats `protobuf:"bytes,5,opt,name=serviceStats,proto3" json:"serviceStats,omitempty"`
	// Statistics for the Node Reflector
	NodeStats *KsrStats `protobuf:"bytes,6,opt,name=nodeStats,proto3" json:"nodeStats,omitempty"`
	// Statistics for the SfcPod Reflector
	SfcPodStats *KsrStats `protobuf:"bytes,7,opt,name=sfcPodStats,proto3" json:"sfcPodStats,omitempty"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ksr_nb_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_ksr_nb_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_ksr_nb_api_proto_rawDescGZIP(), []int{1}
}

func (x *Stats) GetNamespaceStats() *KsrStats {
	if x != nil {
		return x.NamespaceStats
	}
	return nil
}

func (x *Stats) GetPodStats() *KsrStats {
	if x != nil {
		return x.PodStats
	}
	return nil
}

func (x *Stats) GetPolicyStats() *KsrStats {
	if x != nil {
		return x.PolicyStats
	}
	return nil
}

func (x *Stats) GetEndpointsStats() *KsrStats {
	if x != nil {
		return x.EndpointsStats
	}
	return nil
}

func (x *Stats) GetServiceStats() *KsrStats {
	if x != nil {
		return x.ServiceStats
	}
	return nil
}

func (x *Stats) GetNodeStats() *KsrStats {
	if x != nil {
		return x.NodeStats
	}
	return nil
}

func (x *Stats) GetSfcPodStats() *KsrStats {
	if x != nil {
		return x.SfcPodStats
	}
	return nil
}

var File_ksr_nb_api_proto protoreflect.FileDescriptor

var file_ksr_nb_api_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6b, 0x73, 0x72, 0x5f, 0x6e, 0x62, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6b, 0x73, 0x72, 0x61, 0x70, 0x69, 0x22, 0x82, 0x02, 0x0a, 0x08, 0x4b,
	0x73, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x41, 0x64, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x52, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x64, 0x64,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x64,
	0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x55, 0x70, 0x64, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x44, 0x65, 0x6c, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x72, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x41, 0x72, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x52, 0x65, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22,
	0xf7, 0x02, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x0e, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x73, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x4b, 0x73, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x73, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x4b,
	0x73, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x08, 0x70, 0x6f, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x32, 0x0a, 0x0b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x73, 0x72, 0x61, 0x70, 0x69, 0x2e,
	0x4b, 0x73, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x0b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x0e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6b, 0x73, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x4b, 0x73, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x0e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x34, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x73, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x4b,
	0x73, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x73, 0x72, 0x61, 0x70,
	0x69, 0x2e, 0x4b, 0x73, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x0b, 0x73, 0x66, 0x63, 0x50, 0x6f, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x73, 0x72,
	0x61, 0x70, 0x69, 0x2e, 0x4b, 0x73, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x0b, 0x73, 0x66,
	0x63, 0x50, 0x6f, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6b,
	0x73, 0x72, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ksr_nb_api_proto_rawDescOnce sync.Once
	file_ksr_nb_api_proto_rawDescData = file_ksr_nb_api_proto_rawDesc
)

func file_ksr_nb_api_proto_rawDescGZIP() []byte {
	file_ksr_nb_api_proto_rawDescOnce.Do(func() {
		file_ksr_nb_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_ksr_nb_api_proto_rawDescData)
	})
	return file_ksr_nb_api_proto_rawDescData
}

var file_ksr_nb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ksr_nb_api_proto_goTypes = []interface{}{
	(*KsrStats)(nil), // 0: ksrapi.KsrStats
	(*Stats)(nil),    // 1: ksrapi.Stats
}
var file_ksr_nb_api_proto_depIdxs = []int32{
	0, // 0: ksrapi.Stats.namespaceStats:type_name -> ksrapi.KsrStats
	0, // 1: ksrapi.Stats.podStats:type_name -> ksrapi.KsrStats
	0, // 2: ksrapi.Stats.policyStats:type_name -> ksrapi.KsrStats
	0, // 3: ksrapi.Stats.endpointsStats:type_name -> ksrapi.KsrStats
	0, // 4: ksrapi.Stats.serviceStats:type_name -> ksrapi.KsrStats
	0, // 5: ksrapi.Stats.nodeStats:type_name -> ksrapi.KsrStats
	0, // 6: ksrapi.Stats.sfcPodStats:type_name -> ksrapi.KsrStats
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ksr_nb_api_proto_init() }
func file_ksr_nb_api_proto_init() {
	if File_ksr_nb_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ksr_nb_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KsrStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ksr_nb_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ksr_nb_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ksr_nb_api_proto_goTypes,
		DependencyIndexes: file_ksr_nb_api_proto_depIdxs,
		MessageInfos:      file_ksr_nb_api_proto_msgTypes,
	}.Build()
	File_ksr_nb_api_proto = out.File
	file_ksr_nb_api_proto_rawDesc = nil
	file_ksr_nb_api_proto_goTypes = nil
	file_ksr_nb_api_proto_depIdxs = nil
}
