// Copyright (c) 2019 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: customnetwork.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomNetwork_Type int32

const (
	CustomNetwork_L2 CustomNetwork_Type = 0
	CustomNetwork_L3 CustomNetwork_Type = 1
)

// Enum value maps for CustomNetwork_Type.
var (
	CustomNetwork_Type_name = map[int32]string{
		0: "L2",
		1: "L3",
	}
	CustomNetwork_Type_value = map[string]int32{
		"L2": 0,
		"L3": 1,
	}
)

func (x CustomNetwork_Type) Enum() *CustomNetwork_Type {
	p := new(CustomNetwork_Type)
	*p = x
	return p
}

func (x CustomNetwork_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomNetwork_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_customnetwork_proto_enumTypes[0].Descriptor()
}

func (CustomNetwork_Type) Type() protoreflect.EnumType {
	return &file_customnetwork_proto_enumTypes[0]
}

func (x CustomNetwork_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomNetwork_Type.Descriptor instead.
func (CustomNetwork_Type) EnumDescriptor() ([]byte, []int) {
	return file_customnetwork_proto_rawDescGZIP(), []int{0, 0}
}

// CustomNetwork is used to store definition of custom network defined via CRD.
type CustomNetwork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the custom network
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type of the custom network
	Type CustomNetwork_Type `protobuf:"varint,2,opt,name=type,proto3,enum=model.CustomNetwork_Type" json:"type,omitempty"`
	// subnet of the custom network
	SubnetCIDR string `protobuf:"bytes,3,opt,name=subnetCIDR,proto3" json:"subnetCIDR,omitempty"`
	// prefix length defining network subnet used for each node in the cluster
	SubnetOneNodePrefix uint32 `protobuf:"varint,4,opt,name=subnet_one_node_prefix,json=subnetOneNodePrefix,proto3" json:"subnet_one_node_prefix,omitempty"`
}

func (x *CustomNetwork) Reset() {
	*x = CustomNetwork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customnetwork_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomNetwork) ProtoMessage() {}

func (x *CustomNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_customnetwork_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomNetwork.ProtoReflect.Descriptor instead.
func (*CustomNetwork) Descriptor() ([]byte, []int) {
	return file_customnetwork_proto_rawDescGZIP(), []int{0}
}

func (x *CustomNetwork) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomNetwork) GetType() CustomNetwork_Type {
	if x != nil {
		return x.Type
	}
	return CustomNetwork_L2
}

func (x *CustomNetwork) GetSubnetCIDR() string {
	if x != nil {
		return x.SubnetCIDR
	}
	return ""
}

func (x *CustomNetwork) GetSubnetOneNodePrefix() uint32 {
	if x != nil {
		return x.SubnetOneNodePrefix
	}
	return 0
}

var File_customnetwork_proto protoreflect.FileDescriptor

var file_customnetwork_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xbf, 0x01, 0x0a,
	0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x43, 0x49, 0x44, 0x52, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x43, 0x49, 0x44,
	0x52, 0x12, 0x33, 0x0a, 0x16, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x6f, 0x6e, 0x65, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x13, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0x16, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06,
	0x0a, 0x02, 0x4c, 0x32, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x33, 0x10, 0x01, 0x42, 0x03,
	0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_customnetwork_proto_rawDescOnce sync.Once
	file_customnetwork_proto_rawDescData = file_customnetwork_proto_rawDesc
)

func file_customnetwork_proto_rawDescGZIP() []byte {
	file_customnetwork_proto_rawDescOnce.Do(func() {
		file_customnetwork_proto_rawDescData = protoimpl.X.CompressGZIP(file_customnetwork_proto_rawDescData)
	})
	return file_customnetwork_proto_rawDescData
}

var file_customnetwork_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_customnetwork_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_customnetwork_proto_goTypes = []interface{}{
	(CustomNetwork_Type)(0), // 0: model.CustomNetwork.Type
	(*CustomNetwork)(nil),   // 1: model.CustomNetwork
}
var file_customnetwork_proto_depIdxs = []int32{
	0, // 0: model.CustomNetwork.type:type_name -> model.CustomNetwork.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_customnetwork_proto_init() }
func file_customnetwork_proto_init() {
	if File_customnetwork_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_customnetwork_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomNetwork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_customnetwork_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customnetwork_proto_goTypes,
		DependencyIndexes: file_customnetwork_proto_depIdxs,
		EnumInfos:         file_customnetwork_proto_enumTypes,
		MessageInfos:      file_customnetwork_proto_msgTypes,
	}.Build()
	File_customnetwork_proto = out.File
	file_customnetwork_proto_rawDesc = nil
	file_customnetwork_proto_goTypes = nil
	file_customnetwork_proto_depIdxs = nil
}
